version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: jobhunting
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d jobhunting"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/jobhunting
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./api:/app

  worker:
    build: ./api
    command: celery -A app.celery worker --loglevel=info
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      api:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/jobhunting
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./api:/app

  web:
    build: ./web
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_started
    environment:
      # IMPORTANT: Browser needs host URL, not docker service name
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./web:/usr/src/app

volumes:
  postgres_data:

